"""
Security and API Key Router
===========================
Endpoints for creating, listing, and revoking API keys.
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime

from app.database import get_db
from app.core.dependencies import require_real_user
from app.models import User, ApiKey
from app.services.api_key_service import (
    generate_user_api_key,
    revoke_user_api_key,
)

router = APIRouter(prefix="/api/security", tags=["Security & API Keys"])


# ─── Schemas ──────────────────────────────────────────────────────────────────

class ApiKeyCreateRequest(BaseModel):
    description: Optional[str] = None

class ApiKeyResponse(BaseModel):
    id: int
    key_preview: str
    description: Optional[str]
    is_active: bool
    created_at: datetime
    last_used_at: Optional[datetime]

    class Config:
        from_attributes = True

class ApiKeyCreatedResponse(BaseModel):
    id: int
    api_key: str
    description: Optional[str]
    message: str


# ─── Endpoints ─────────────────────────────────────────────────────────────────

@router.post("/keys", response_model=ApiKeyCreatedResponse, status_code=201)
def create_key(
    body: ApiKeyCreateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_real_user),
):
    """
    Generate a new programmatic access API key.
    The key is only shown once upon creation.
    """
    raw_key = generate_user_api_key(db, current_user.id, body.description)
    
    # Fetch the generated key record to return its DB ID
    db_key = db.query(ApiKey).filter(ApiKey.key == raw_key).first()
    
    return ApiKeyCreatedResponse(
        id=db_key.id if db_key else 0,
        api_key=raw_key,
        description=body.description,
        message="API key created successfully. Store this key securely; it will not be displayed again.",
    )


@router.get("/keys", response_model=List[ApiKeyResponse])
def list_keys(
    db: Session = Depends(get_db),
    current_user: User = Depends(require_real_user),
):
    """
    List all API keys generated by the current user.
    Hides the actual raw secret key, showing only a preview of the prefix.
    """
    keys = db.query(ApiKey).filter(ApiKey.user_id == current_user.id).order_by(ApiKey.created_at.desc()).all()
    
    out = []
    for k in keys:
        preview = f"{k.key[:8]}...{k.key[-4:]}" if len(k.key) > 12 else "nm_..."
        out.append(ApiKeyResponse(
            id=k.id,
            key_preview=preview,
            description=k.description,
            is_active=k.is_active,
            created_at=k.created_at,
            last_used_at=k.last_used_at,
        ))
    return out


@router.delete("/keys/{key_id}", status_code=200)
def revoke_key(
    key_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_real_user),
):
    """
    Revoke programmatic access for a specific API key.
    """
    success = revoke_user_api_key(db, key_id, current_user.id)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="API key not found or not owned by user",
        )
    return {"success": True, "message": "API key revoked successfully."}
