"""add_english_translation_to_messages

Revision ID: 2a5c323ab882
Revises: 6c8e3df8b7f1
Create Date: 2026-07-05 13:43:28.227032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5c323ab882'
down_revision: Union[str, Sequence[str], None] = '6c8e3df8b7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('english_translation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'english_translation')
    # ### end Alembic commands ###
