"""add_session_type_and_doc_id

Revision ID: 966e7e28c082
Revises: 003_drop_otp_requests
Create Date: 2026-07-13 23:00:24.045479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966e7e28c082'
down_revision: Union[str, Sequence[str], None] = '003_drop_otp_requests'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_type', sa.String(), server_default='chat', nullable=False))
    op.add_column('sessions', sa.Column('source_document_id', sa.Integer(), nullable=True))
    
    # SQLite dialect does not support ALTER table foreign key constraints. We only add it for other databases like Postgres.
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.create_foreign_key('fk_sessions_documents', 'sessions', 'documents', ['source_document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.drop_constraint('fk_sessions_documents', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'source_document_id')
    op.drop_column('sessions', 'session_type')
    # ### end Alembic commands ###



